### PR TITLE
Adding functionality to resolve symlinks

### PR DESCRIPTION
**Pull request by who**
This fixes https://github.com/mihaip/dex-method-counts/issues/10

### CODE REVIEW

**Comment by niedzielski** [comment]
This is a one-liner with readlink. Isn't it a reasonable dependency?

**Comment by who** [comment]
@niedzielski It can only be a one-liner on Linux, as Max OSX does not support `readlink -f`.

My PR is tested on OS X (Yosemite) and Linux (Ubuntu 14.04).

**Comment by niedzielski** [comment]
Is it unreasonable to expect users to install Hombrew or another package
manager?

**Comment by who** [comment]
@niedzielski 

> Is it unreasonable to expect users to install Hombrew or another package
manager?

I personally don't think its unreasonable, but not everyone uses Homebrew.  I wanted to present a stand-alone solution.  

Here's how we could do it with Homebrew:

`brew install coreutils`

and then

`greadlink -f`

**Comment by mihaip** [comment]
Thanks!

**Pull request merged**
