### PR TITLE
Adds a new flag —output_style which defaults to TREE (the current

### PR DESCRIPTION
**Pull request by brianduff**
implementation), but supports FLAT. In FLAT output mode, the output is
dumped in a format that resembles that of the dex tool itself when you
exceed the method limit (flat list of packages proceeded by their
package list).

### CODE REVIEW

**Comment by brianduff** [comment]
ping

**Comment by sschuberth** [comment]
@brianduff Sorry Brian, I guess the merge of my PR #13 now causes a conflict for you. Could you please fix it, and then ping @mihaip in case he's not watching for PRs being created?

**Comment by brianduff** [comment]
I've pinged several times on this, I'm unlikely to spend any more time on
it.

**Comment by jaredsburrows** [comment]
@brianduff @mihaip Just fix the conflicts.

**Comment by sschuberth** [comment]
I took the liberty to resolve the conflicts and reword the commit message a bit: https://github.com/mihaip/dex-method-counts/pull/14.

**Comment by jaredsburrows** [comment]
You have to keep pinging @mihaip

**Comment by mihaip** [comment]
Supplanted by #14, sorry for the delay.

**Pull request closed without merging**
